In [1]:
import pandas as pd

In [2]:
path_submission = '/Users/celinegianduzzo/code/theresa-sporn/WorkforceSentimentMonitoring/raw_data/sample_submission.csv'

In [3]:
submission = pd.read_csv(path_submission)

In [4]:
submission.shape

(29272, 2)

In [5]:
submission.tail()

          ID  overall
29267  66959        4
29268  66965        2
29269  66968        3
29270  66978        1
29271  66986        4

In [6]:
path_train = '/Users/celinegianduzzo/code/theresa-sporn/WorkforceSentimentMonitoring/raw_data/train.csv'

train = pd.read_csv(path_train)

In [7]:
path_test = '/Users/celinegianduzzo/code/theresa-sporn/WorkforceSentimentMonitoring/raw_data/test.csv'

test = pd.read_csv(path_test)

In [8]:
train.shape

(30336, 17)

In [9]:
test.shape

(29272, 16)

In [10]:
test = pd.merge(test, submission, on=['ID'])

In [11]:
test

,ID,Place,location,date,status,job_title,summary,positives,negatives,advice_to_mgmt,score_1,score_2,score_3,score_4,score_5,score_6,overall
0,5,startup_1,"Los Angeles, CA","Jul 19, 2018",Former Employee,Software Engineer,"Unique, one of a kind dream job",Google is a world of its own. At every other c...,"If you don't work in MTV (HQ), you will be giv...",Promote managers into management for their man...,5,5,5,5,5,49,5
1,6,startup_1,"Mountain View, CA","Dec 9, 2018",Former Employee,SDE2,NICE working in GOOGLE as an INTERN,"People are not that busy, so they are nice to ...",Food is not good as I expected. People said it...,NaN,4,4,4,5,4,1,4
2,7,startup_1,"New York, NY","Dec 11, 2018",Current Employee,Software Engineer,Software engineer,Great working environment. Good work life balance,Usual big company problems. Hierarchy.,NaN,5,4,4,5,4,0,4
3,8,startup_1,NaN,"Dec 11, 2018",Former Employee,Anonymous Employee,great place to work and progress,"work culture, benefits, growth, people,",No cons that i can think of,NaN,5,5,5,5,5,0,5
4,9,startup_1,"New York, NY","Dec 10, 2018",Current Employee,Anonymous Employee,Google Surpasses Realistic Expectations,Great products. Vision you can feel good about...,Younger employees complaining about the compan...,NaN,5,5,5,5,5,0,5
5,11,startup_1,"Mountain View, CA","Dec 8, 2018",Current Employee,Anonymous Employee,Nice place to work,* Smart people * World class infrastructure * ...,Giant company with uneven project and team cha...,NaN,4,5,4,4,3,0,3
6,12,startup_1,NaN,"Dec 8, 2018",Current Employee,Anonymous Employee,Software Engineer,* There is endless opportunity * You'll never ...,* There's always someone better than you. * Yo...,NaN,5,5,5,5,5,0,5
7,13,startup_1,NaN,"Dec 4, 2018",Former Employee,Anonymous Employee,Best Company to Work For!,Atmosphere that promotes the expression of fre...,It can be an overwhelming machine at times but...,NaN,5,5,5,5,5,1,5
8,14,startup_1,"San Francisco, CA","Dec 3, 2018",Current Employee,Sales Operations Analyst,Still the best place to work!,Amazing company. Still the best place to work.,"Size, which limits opportunities for extraordi...",NaN,5,5,5,4,4,1,4
9,15,startup_1,NaN,"Dec 6, 2018",Current Employee,Anonymous Employee,Mba Intern,"Perks, autonomy, cool products, smart people",Slow career progression for non-tech,NaN,4,5,3,5,5,0,5
10,20,startup_1,NaN,"Dec 3, 2018",Current Employee,Anonymous Employee,Senior Account Manager,"Great benefits, growth and people to work with...",Must be located in an office,NaN,5,5,5,5,5,0,5
11,21,startup_1,"New York, NY","Nov 26, 2018",Current Employee,Designer,"Great, but great can always be better",Great team and support for individuals,"Lots of bureaucracy, not super diverse",NaN,3,4,3,4,5,2,5
12,22,startup_1,NaN,"Dec 2, 2018",Current Employee,Anonymous Employee,Great company to work for,I love Google a lot,Some things are not to great,NaN,5,5,5,5,5,0,5
13,26,startup_1,NaN,"Nov 29, 2018",Current Employee,Anonymous Employee,Good Company to Work for,"- perks are phenomenal, food, health, office",- work life balance is hard to manage,NaN,4,5,4,5,5,0,5
14,28,startup_1,"San Francisco, CA","Nov 17, 2018",Current Employee,Program Manager I,"Not perfect, but still the best place in the w...","- A company culture that encourages dissent, d...",- A company with over 90k people at the time o...,- Just because a small percentage of the compa...,5,5,5,5,5,3,5
15,33,startup_1,NaN,"Nov 24, 2018",Current Employee,Anonymous Employee,Is very good,is very good. is very very good,You work a lot. Like a lot,NaN,5,5,5,5,5,0,5
16,34,startup_1,"Mountain View, CA","Dec 8, 2018",Current Employee,Software Engineering Manager,Google is still the best place to be,"Great place to work, learn new things, grow an...",Large company issues have crept up but nothing...,NaN,5,5,4,4,4,0,4
17,36,startup_1,NaN,"Nov 19, 2018",Current Employee,Anonymous Employee,Good place to work,Nice perks. Good work life balance,too slow and too much consensus culture someti...,NaN,5,5,5,5,5,1,5
18,37,startup_1,NaN,"Dec 6, 2018",Current Employee,Anonymous Employee,Senior Software Engineer,Good work and life balance,Growth of salaries and career opportunities,NaN,5,4,3,4,3,0,3
19,39,startup_1,NaN,"Dec 6, 2018",Current Employee,Anonymous Employee,"Great perks, bad work-life balance","Google’s perks are great: free food, shuttle t...",I have zero work-life balance. I work minimum ...,Restructure performance reviews so that some f...,2,3,5,5,3,0,3
20,43,startup_1,NaN,"Dec 4, 2018",Former Employee,Anonymous Employee,Big Tech,Never have to skip a paycheck.,Google has an over abundance of technicians an...,NaN,3,2,3,4,1,0,1
21,49,startup_1,NaN,"Dec 2, 2018",Current Employee,Anonymous Employee,g,"perks are pretty good, as is culture",work/life balance is generally moderate to poor,NaN,2,4,4,5,4,0,4
22,53,startup_1,"Mountain View, CA","Nov 9, 2018",Current Employee,Software Engineer,Best Job I Ever Had,Amazing and talented co workers best place to ...,All the perks makes me not want to leave work,NaN,5,5,5,5,5,1,5
23,55,startup_1,"New York, NY","Nov 4, 2018",Current Employee,Software Engineer,Top Tech Company in the World,"Brilliant colleagues, excellent engineering st...",Promotions are extremely demanding. When in do...,NaN,5,5,5,4,4,2,4
24,56,startup_1,NaN,"Nov 22, 2018",Current Employee,Data Scientist,Depends on what you're looking for,For the right people it can be a great place. ...,Projects can be boring or useless. Work may no...,NaN,4,3,2,5,2,2,2
25,57,startup_1,NaN,"Nov 20, 2018",Current Employee,Anonymous Employee,Senior Software Engineer,"Brilliant people, tons of awesome technical in...",- Skills inside Google aren't always easily tr...,NaN,4,4,4,5,3,1,3
26,60,startup_1,NaN,"Nov 21, 2018",Current Employee,Anonymous Employee,"Good Company, can be long hours","great benefits, great people, dynamic environment","Depending on the department and clients, hours...",NaN,3,4,4,5,4,0,4
27,63,startup_1,NaN,"Nov 21, 2018",Former Employee,Anonymous Employee,not too bad,nice food，nice place ，nice people,i cannot understand what they talk,NaN,3,3,4,4,2,0,2
28,64,startup_1,"New York, NY","Nov 5, 2018",Former Employee,Anonymous Employee,Outstanding,"All good, excellent benefits, okay salary","Computerized humans, too much pressure",Humanize the company,2,2,4,4,3,0,3
29,68,startup_1,NaN,"Nov 19, 2018",Former Employee,Anonymous Employee,Engineer,salary was fine but in line with other companies,work was boring. I disliked it.,NaN,3,3,2,3,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29242,66891,startup_6,Hyderabad (India),"Jun 21, 2012",Former Employee,Software Development Engineer,"Good company, your immediate manager has VETO ...",1. Good work culture. 2. Friendly and helping...,"1. If your manager is not satisfied, or for so...",NaN,3,3,3,3,3,1,3
29243,66892,startup_6,Dubai (United Arab Emirates),"Jun 25, 2012",Current Employee,Solution Specialist,Not bad,Good Enough Big Company Lots to learn,Process oriented Too many meetings Monotonous ...,More concentration results and less on processes,4,4,2,3,3,0,3
29244,66895,startup_6,Kuala Lumpur (Malaysia),"Jun 18, 2012",Former Employee,Enterprise Technology Strategist,A company losing focus,A chance to help companies and individuals ach...,MS is focusing solely on revenue now. Even par...,Revenue is not everything. Record revenues hav...,4,1,2,3,1,3,1
29245,66896,startup_6,Hyderabad (India),"Jun 28, 2012",Current Employee,TECHNOLOGIST SAP,Been a great learning experience everyday at w...,Open and Honest Culture. Ability to speak your...,Difficult to breakthrough to higher levels wit...,"Constant Organization changes, can sometimes a...",5,4,4,4,4,0,4
29246,66898,startup_6,NaN,"Jun 16, 2012",Former Employee,Software Development Engineer In Test,"Good company, bad management",Very bright people and lot of avenues for lear...,Most of the managers are in the management jus...,Focus on innovation and growing people careers...,2,3,4,3,2,2,2
29247,66899,startup_6,Singapore (Singapore),"Jun 27, 2012",Former Employee,IT Systems Specialist,IT system specialist,"Great workig environment, helping peers",organization changes too quick with insufficie...,NaN,5,4,2,4,4,0,4
29248,66903,startup_6,NaN,"Jun 23, 2012",Former Employee,Legal and Corporate Affairs,Great place to grow and learn from the best in...,"Amazing ressources available, has a global imp...","Microsoft is rather big and bureaucratic, and ...",NaN,3,4,4,5,4,0,4
29249,66905,startup_6,NaN,"Jun 12, 2012",Current Employee,Anonymous Employee,MS review,"Good infrastructure, Work from home, Very tale...",Very competitive environment to work,NaN,5,5,5,5,5,0,5
29250,66907,startup_6,"Reading, England (UK)","Jun 21, 2012",Current Employee,Technical Lead,Fantastic place to work and develop,"Great set of benefits, flexible working enviro...",Salary is somewhat slightly below market avera...,NaN,5,5,4,3,5,0,5
29251,66909,startup_6,NaN,"Jun 12, 2012",Current Employee,Anonymous Employee,The Dream is Over,The pay and benefits are alright,It's more about politics than building great p...,NaN,2,2,3,4,2,2,2
29252,66911,startup_6,Hyderabad (India),"Jun 12, 2012",Current Employee,Associate Consultant,Associate Consultant,Very Nice and people friendly company,Projects are not very good,NaN,4,5,4,5,4,0,4
29253,66915,startup_6,NaN,"Jun 12, 2012",Current Employee,Anonymous Employee,Great company,lots of things to work on and always changing,can be demanding and long hours,NaN,4,4,5,4,4,0,4
29254,66921,startup_6,Bengaluru (India),"Jun 30, 2012",Current Employee,Technical Support Engineer,Review,Loads of technical stuff to learn & good resou...,Its full of politics. Dont even dare to enter ...,I have lost hope that things would ever change...,1,1,1,3,1,7,1
29255,66922,startup_6,NaN,"Jun 7, 2012",Current Employee,Interaction Designer,Great opportunity to create products that can ...,Opportunity to create products that can change...,Need to be aware of politics and know how to n...,NaN,4,4,5,5,3,0,3
29256,66925,startup_6,Bhubaneswar (India),"Jun 6, 2012",Current Employee,Marketing Manager,best employer,remuneration and growth best in industry,hardwork and dedication required at all times,NaN,3,3,3,5,4,0,4
29257,66926,startup_6,Hyderabad (India),"Jun 6, 2012",Former Employee,Test Lead,Wonderful working with Microsoft,"Best place to work, excellent work environment...",Nothing much to say in cons. The joy of workin...,NaN,5,5,5,5,5,0,5
29258,66931,startup_6,NaN,"Jun 13, 2012",Current Employee,Anonymous Employee,Learning opportunity good friendly environment,"Friendly environment, Learning Opportunities, ...","Do not have many companies in Lucknow, so one ...",Keep up the good work,4,4,3,2,5,0,5
29259,66933,startup_6,NaN,"Jun 13, 2012",Current Employee,Anonymous Employee,Microsoft Services,1. One of the best culture. 2. Lots of values ...,1. Some times work life balance is poor,NaN,2,5,5,3,2,0,2
29260,66934,startup_6,Hyderabad (India),"Jun 14, 2012",Former Employee,Software Development Engineer,Great company to be a part of,Brand name Work environment Flexi timing Chall...,Competition with great talents :),NaN,5,5,3,4,4,0,4
29261,66936,startup_6,NaN,"Jun 12, 2012",Current Employee,Anonymous Employee,Great and Stable place to work,"You will be in the company of Smart, Intellige...",You might feel disconnected from the outside r...,NaN,4,4,3,4,2,0,2
29262,66937,startup_6,Chennai (India),"Jun 7, 2012",Current Employee,Law Internship,It's not a big one. but a very descent place t...,The Employer is a very friendly and kind perso...,No Salary for the Internees.,NaN,3,3,4,2,4,1,4
29263,66941,startup_6,NaN,"Jun 7, 2012",Current Employee,Anonymous Employee,very good company,"People are smart (but still not enough), polit...",Some people are very political. Innovation is ...,NaN,4,3,3,3,4,0,4
29264,66946,startup_6,Hyderabad (India),"Jun 1, 2012",Current Employee,Senior Program Manager,MS India,Good preview to latest technologies,bad management and performance evaluation mech...,NaN,4,3,3,3,2,2,2
29265,66952,startup_6,Hyderabad (India),"Jun 5, 2012",Current Employee,Software Development Engineer In Test (SDET),Awesome work environment,"Brand name: Whatever the case, Microsoft will ...",Lack of knowledge growth: Compared to small co...,There is lack of innovation as compared to wha...,4,4,4,4,3,0,3
29266,66955,startup_6,NaN,"Jun 2, 2012",Current Employee,Anonymous Employee,"Good company, very demanding, and too much use...","Strong financials, good comps, name recognition.","Very demanding, revenue based, global nature d...","Streamline antiquated processes, trim upper ma...",3,3,3,4,3,0,3
29267,66959,startup_6,NaN,"Jun 4, 2012",Current Employee,Solution Specialist,great place to grow!,Great health benefits. Many internal job oppor...,Red Tape. Tough to negotiate internal politics...,NaN,4,4,5,4,4,0,4
29268,66965,startup_6,NaN,"May 31, 2012",Current Employee,Senior Program Manager,An ocean of opportunities,diverse set of people and problems they solve....,sometimes feels like a behemoth trying to get ...,align workgroups and incentives better to crea...,1,3,5,4,2,0,2
29269,66968,startup_6,NaN,"Jun 1, 2012",Current Employee,Software Development Engineer In Test (SDET),Tech Gaint,Equip its employees wid huge salaries :D,High qualification required to join it,Good Going....try searching new and bigger tal...,3,3,3,3,3,0,3
29270,66978,startup_6,NaN,"Jun 8, 2012",Former Employee,Senior Systems Engineer,Terrible,They had great health benefits (no longer im t...,* 14 hour days * no idea how to run a service ...,Learn to excel (no pun intended) and ignore mo...,1,1,1,3,1,3,1
29271,66986,startup_6,Hyderabad (India),"May 26, 2012",Current Employee,Program Manager,Microsoft is a good place to work,Very structured organization Market focused pr...,Growth is a little slow - Good structure impli...,NaN,4,4,4,3,4,0,4

In [12]:
train

,ID,Place,location,date,status,job_title,summary,positives,negatives,advice_to_mgmt,score_1,score_2,score_3,score_4,score_5,score_6,overall
0,1,startup_1,NaN,"Dec 11, 2018",Current Employee,Anonymous Employee,Best Company to work for,People are smart and friendly,Bureaucracy is slowing things down,NaN,4.0,5.0,5.0,4.0,5.0,0,5.0
1,2,startup_1,"Mountain View, CA","Jun 21, 2013",Former Employee,Program Manager,"Moving at the speed of light, burn out is inev...","1) Food, food, food. 15+ cafes on main campus ...",1) Work/life balance. What balance? All those ...,1) Don't dismiss emotional intelligence and ad...,2.0,3.0,3.0,5.0,3.0,2094,5.0
2,3,startup_1,"New York, NY","May 10, 2014",Current Employee,Software Engineer III,Great balance between big-company security and...,"* If you're a software engineer, you're among ...","* It *is* becoming larger, and with it comes g...",Keep the focus on the user. Everything else wi...,5.0,4.0,5.0,5.0,4.0,949,5.0
3,4,startup_1,"Mountain View, CA","Feb 8, 2015",Current Employee,Anonymous Employee,The best place I've worked and also the most d...,You can't find a more well-regarded company th...,I live in SF so the commute can take between 1...,Keep on NOT micromanaging - that is a huge ben...,2.0,5.0,5.0,4.0,5.0,498,4.0
4,10,startup_1,NaN,"Dec 9, 2018",Current Employee,Anonymous Employee,Execellent for engineers,Impact driven. Best tech in the world.,Size matters. Engineers are a bit disconnected...,NaN,5.0,5.0,5.0,5.0,5.0,0,4.0
5,16,startup_1,NaN,"Dec 6, 2018",Current Employee,Anonymous Employee,Review,The people are great to work with,There is lower compensation than expected,NaN,NaN,NaN,NaN,NaN,NaN,0,5.0
6,17,startup_1,NaN,"Nov 29, 2018",Current Employee,Anonymous Employee,Review of Google,"The people are great to work with, good perks.",Wide variety in experience based on team.,NaN,4.0,5.0,5.0,5.0,4.0,2,3.0
7,18,startup_1,NaN,"Dec 2, 2018",Former Employee,Anonymous Employee,Analysts,"Good managers, benefits , some support, nice a...","Long hours, far locations, a lot of work",NaN,NaN,NaN,2.0,NaN,NaN,1,5.0
8,19,startup_1,NaN,"Dec 1, 2018",Former Employee,Anonymous Employee,Great Company With No Down Sides,Really fun work environment with startup,Really no down sides that I saw.,NaN,5.0,5.0,5.0,5.0,5.0,1,5.0
9,24,startup_1,NaN,"Nov 30, 2018",Current Employee,Anonymous Employee,Software Engineer,Awesome job environment to work in,Pressure is there for some parts,NaN,NaN,NaN,NaN,NaN,NaN,0,5.0
10,25,startup_1,"Los Angeles, CA","Nov 29, 2018",Current Employee,Staff Accountant,Accountant,I like and learned from the beginning accounting,High clerical work in the Sane record,Management and Finance must be close relation ...,5.0,5.0,5.0,5.0,5.0,0,4.0
11,27,startup_1,NaN,"Nov 28, 2018",Current Employee,Anonymous Employee,Great culture,Very inspiring engineers to work with.,"Easy to get lost, as it is such a big company.",NaN,3.0,5.0,4.0,5.0,3.0,0,3.0
12,29,startup_1,NaN,"Nov 27, 2018",Current Employee,Anonymous Employee,Great place to work,The people are awesome. Lots of perks. Reduce ...,There's sometimes too wide a variety of things...,NaN,4.0,5.0,5.0,5.0,5.0,0,3.0
13,32,startup_1,"Mountain View, CA","Dec 9, 2018",Former Employee,Senior Director,Senior Director,So many brilliant people Tons of resources Wor...,Becoming highly bureaucratic Growing political...,NaN,4.0,5.0,5.0,5.0,5.0,0,5.0
14,35,startup_1,"Dearborn, MI","Nov 20, 2018",Current Employee,Google Specialist,Google,Google is one of the beast Company in the world,You have to work hard,NaN,3.0,4.0,4.0,5.0,4.0,1,4.0
15,38,startup_1,"New York, NY","Dec 6, 2018",Current Employee,Anonymous Employee,Good compensation,Better than average engineers. Competitive com...,Big and beurocratic. Lots of legacy systems. M...,NaN,4.0,3.0,3.0,4.0,3.0,0,2.0
16,40,startup_1,"Sunnyvale, CA","Nov 21, 2018",Current Employee,Anonymous Employee,Best of the best,"The best company I've worked for. Culture, per...","Set hours for breakfast, lunch, dinner.",NaN,3.0,5.0,5.0,5.0,4.0,0,3.0
17,41,startup_1,NaN,"Dec 4, 2018",Current Employee,Anonymous Employee,Manager,Easy place and people are nice,Employee will require muti-tasking to complete...,NaN,NaN,NaN,NaN,NaN,NaN,0,4.0
18,42,startup_1,"Seattle, WA","Nov 13, 2018",Current Employee,Staff Software Engineer,Hard to beat,Amazing compensation + benefits (hard to beat ...,Growing pains as Google has gone from ~10k to ...,NaN,4.0,4.0,5.0,5.0,3.0,2,4.0
19,44,startup_1,"New York, NY","Nov 19, 2018",Current Employee,Program Manager,Great place to work,"Ambitious mission, great colleagues, supportiv...","Everyone is eager to succeed, which can lead t...",NaN,5.0,3.0,5.0,4.0,5.0,0,4.0
20,45,startup_1,"Sunnyvale, CA","Nov 19, 2018",Current Employee,Software Engineer,Positive Experiences,Good opportunities for different technical exp...,Difficult to advance depending on which projec...,NaN,5.0,5.0,4.0,4.0,4.0,0,4.0
21,47,startup_1,"Ann Arbor, MI","Nov 19, 2018",Former Employee,Associate Account Strategist,Make sure you know what role you're applying for,"Employees, food, benefits, perks, shuttle, bas...","Company has become way too vertical, performan...","Stop putting people on a bell curve, and recog...",4.0,4.0,5.0,5.0,2.0,0,5.0
22,48,startup_1,NaN,"Dec 2, 2018",Current Employee,Anonymous Employee,Its Google,"food, shuttle, technology, perks, health, 401K...",Great place to work finace is backend though. ...,NaN,4.0,4.0,4.0,4.0,3.0,0,3.0
23,50,startup_1,"Mountain View, CA","Nov 16, 2018",Current Employee,Anonymous Employee,meh,Pays really well Free food Looks good on resume,Google wants 60-hour weeks. If you have a 150 ...,Add ethics to the review process A launch is n...,2.0,1.0,2.0,5.0,2.0,8,3.0
24,51,startup_1,NaN,"Nov 15, 2018",Current Employee,Anonymous Employee,Good place,Pretty good benifits and bank.,Being challanged everyday. Having no life.,NaN,NaN,NaN,5.0,NaN,NaN,0,5.0
25,52,startup_1,NaN,"Nov 27, 2018",Former Employee,Anonymous Employee,cs analyst,"great work culture , good for starters",long hours can be unreasonable,"none, doing fantastic",NaN,NaN,NaN,NaN,NaN,0,4.0
26,58,startup_1,NaN,"Nov 5, 2018",Current Employee,Anonymous Employee,Google Summer Internship,Great pay Great work life balance Great perks/...,"Very few, work sometimes monotonous.",NaN,5.0,5.0,5.0,5.0,5.0,1,4.0
27,59,startup_1,NaN,"Nov 22, 2018",Current Employee,Anonymous Employee,good place,"comfortable environment, free food, nice people",difficult to promote in google,NaN,NaN,NaN,NaN,NaN,NaN,0,4.0
28,61,startup_1,NaN,"Nov 6, 2018",Former Employee,Anonymous Employee,Project Manager,Great company with creative ideas.,No cons at this point.,NaN,NaN,NaN,NaN,NaN,NaN,0,5.0
29,62,startup_1,NaN,"Nov 6, 2018",Current Employee,Software Engineer,Great working environment,Here you receive a great opportunity to solve ...,There's the danger of getting too familiar and...,NaN,5.0,5.0,4.0,5.0,4.0,0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30306,67474,startup_6,NaN,"Feb 11, 2011",Former Employee,Anonymous Employee,"long days, stressful, demanding at times but o...","Benefits, casual environment and company has a...",high demand on personal time. My specific mgmt...,Take the time to learn about what drives your ...,2.0,NaN,3.0,5.0,2.0,1,3.0
30307,67476,startup_6,NaN,"Feb 11, 2011",Current Employee,Anonymous Employee,ok,"work with the smartest people, lots of resourc...","too aggressive, no work life balance at all, v...",NaN,3.0,NaN,2.5,3.0,3.0,1,2.0
30308,67477,startup_6,NaN,"Feb 13, 2011",Current Employee,Anonymous Employee,Good,build valuable experience to enable advancemen...,risk of extreme internal politics interferring...,NaN,3.0,NaN,4.0,4.5,3.0,0,4.0
30309,67484,startup_6,NaN,"Feb 1, 2011",Former Employee,"Director, Product Management","frustrating, due to continuous strategy and pe...",Great company vision and passion for changing ...,"Lack of continuity in strategy, management and...",NaN,3.5,NaN,2.5,3.5,4.0,1,4.0
30310,67488,startup_6,NaN,"Jan 30, 2011",Former Employee,Anonymous Employee,"It was highlighted by fast-paced, innovative w...",You will find passionate coworkers who care ab...,Employees must be successful at operating with...,NaN,3.5,NaN,3.0,4.0,3.0,0,3.0
30311,67490,startup_6,"Mississauga, ON (Canada)","Jan 26, 2011",Former Employee,Analyst,Bad Experience as a Contract worker,"- good environment, talented people, cool tech...",- no full time opportunity at entry level,NaN,5.0,NaN,4.5,1.5,3.5,0,3.0
30312,67491,startup_6,Singapore (Singapore),"Jan 25, 2011",Former Employee,Summer Intern,"Underpaid, undervalued, but fun","Summer internship was generally fun, and allow...",Low in terms of career prospects or really get...,NaN,4.0,NaN,4.0,4.0,4.0,0,4.0
30313,67493,startup_6,"Dublin, Co. Dublin (Ireland)","Jan 25, 2011",Former Employee,Anonymous Employee,"political, corporate, little opportunity for a...",compensation and benefits are good. met good p...,"political, corporate, little opportunity for a...",Need to break down the politics to let real ta...,3.0,NaN,3.0,3.5,2.0,0,2.0
30314,67494,startup_6,NaN,"Jan 25, 2011",Current Employee,Consultant,Fountain head of knowledge...,For technologists a place to work,Too much travel for my role and org as a whole...,NaN,3.0,NaN,3.0,4.5,3.0,0,4.0
30315,67495,startup_6,NaN,"Jan 21, 2011",Current Employee,Software Development Engineer II,Awesome company to work for,Microsoft is a very nice company to work for. ...,In some groups there is lot of internal politi...,NaN,5.0,NaN,4.0,4.5,3.0,0,4.0
30316,67496,startup_6,Bengaluru (India),"Jan 19, 2011",Former Employee,Intern,Great place obviously,people are hard workers. lots to learn from th...,some people are extremely geekish senior manag...,NaN,4.0,NaN,4.0,2.5,3.5,0,4.0
30317,67499,startup_6,NaN,"Jan 15, 2011",Former Employee,Anonymous Employee,"Microsoft is a good company, however, they don...","Excellent benefits, always the latest Microsof...",If you exceed your annual goals and commitment...,Appreciate strong workers at all levels and th...,3.5,NaN,3.5,4.5,2.5,0,3.0
30318,67502,startup_6,Hyderabad (India),"Dec 26, 2010",Former Employee,Operations Analyst,I would definitely join the company if I grab ...,One word - technologies. We are rapidly grabbi...,It takes times to find your way but once you d...,Every manager is unique. Unless you really kno...,5.0,NaN,5.0,5.0,5.0,0,5.0
30319,67504,startup_6,NaN,"Jan 7, 2011",Current Employee,Anonymous Employee,was once a great place to work,still some pockets of good ppl.,was great now filled w/ lots of ppl who outsou...,"change out CEO, change approach to review",2.5,NaN,1.0,4.0,2.0,2,2.0
30320,67505,startup_6,Hyderabad (India),"Jan 6, 2011",Current Employee,Anonymous Employee,Great experience and exposure,"An employee's choice of company, great HR prac...","depending on division, career advancement may ...",NaN,5.0,NaN,3.0,5.0,3.0,0,4.0
30321,67507,startup_6,NaN,"Jan 4, 2011",Former Employee,Account Executive,"It was always difficult, whether it was a mult...",There are some really smart folks working ther...,"Meetings, meetings and more meetings. Secret a...",Do away with annual reviews. Make your manager...,5.0,NaN,2.0,4.0,4.0,2,2.0
30322,67508,startup_6,Hyderabad (India),"Jan 3, 2011",Current Employee,Technical Support Engineer,Great company,1. Good salary 2. Good benefits 3. Overall ver...,It varies from team to team - If you ar estuck...,Nothing much - just keep doing whatever you ar...,3.5,NaN,3.5,5.0,1.0,1,3.0
30323,67511,startup_6,Hyderabad (India),"Jan 4, 2011",Current Employee,Software Development Engineer II,"Work life balance is great, Compensation is no...",Best company for entry level Engineer. Good Wo...,"If you joined on a wrong level, No matter how ...","Promotions need to be more transparent,",4.5,NaN,2.5,1.0,4.0,0,3.0
30324,67513,startup_6,NaN,"Jan 2, 2011",Former Employee,Anonymous Employee,"Overall good, however, it depends on group",Has great benefit package. Most of the time yo...,Takes long time to make a decision. Difficult ...,NaN,3.5,NaN,3.5,4.5,3.0,0,4.0
30325,67514,startup_6,Tokyo (Japan),"Jan 2, 2011",Former Employee,Marketing Specialist,Good career path,You can learn and experience lots of things at...,Difficult to work with some senior management ...,NaN,4.0,NaN,4.0,5.0,4.0,0,3.0
30326,67515,startup_6,NaN,"Jan 3, 2011",Current Employee,Anonymous Employee,A stable company but still is not for lazy people,"- Good benefit so far - Large, lots of variety",- Need to follow many rules/processes,Hold their MS stocks longer,4.0,NaN,4.0,3.5,4.0,0,4.0
30327,67516,startup_6,NaN,"Dec 29, 2010",Current Employee,Operations Manager,A: Who do you work for? Me: Microsoft A: I gue...,"- good benefits and perks, free Windows Phone ...","- your life quality, promotions, recognitions ...","you have more people in the team, not only the...",4.5,NaN,2.0,2.5,3.0,1,3.0
30328,67518,startup_6,NaN,"Dec 30, 2010",Current Employee,Anonymous Employee,if you can work 10-12 hours everyday on regula...,Some really smart people to work with. If you ...,"For working mothers, hard place to grow and ke...",NaN,3.0,NaN,2.5,3.0,2.0,0,3.0
30329,67519,startup_6,NaN,"Dec 29, 2010",Former Employee,Anonymous Employee,Not the cult it used to be - far more a job now,lots of new stuff almost daily,processes are killing it and losing momentum,NaN,2.5,NaN,3.0,4.0,2.0,0,3.0
30330,67521,startup_6,NaN,"Dec 20, 2010",Current Employee,Anonymous Employee,a good learning place,It is a big company. So if you really want to ...,"Like any other big companies, it is sometimes ...",NaN,3.0,NaN,2.5,3.0,4.5,1,4.0
30331,67522,startup_6,NaN,"Dec 22, 2010",Former Employee,Senior Project Managet,Microsoft Services is bad.,MS is a good company but hire wrong people. Wo...,Senior management has no leadership and very o...,Major management revamp esp in APAC. It's not ...,3.0,NaN,1.5,2.0,1.0,0,2.0
30332,67524,startup_6,NaN,"Dec 17, 2010",Former Employee,Senior Program Manager,Good company.,"Good benefits package, huge customer base.","Politics, very slow, lots of dead wood.",Move on.,3.5,NaN,3.5,4.0,4.0,0,4.0
30333,67525,startup_6,NaN,"Dec 16, 2010",Former Employee,Anonymous Employee,Enriching experience for a beginner but bad fo...,"-Access to a wide range of technologies, compl...",-Testers(SDET's ) do not get as many opportuni...,Make the company leaner and Meaner. (which wou...,3.0,NaN,4.0,4.0,2.0,0,3.0
30334,67527,startup_6,NaN,"Dec 15, 2010",Current Employee,Account Manager,Good Place to Work,Nice place to work. Good atmosphere with advan...,Management confusion at times with vision for ...,NaN,3.0,NaN,4.0,4.5,3.5,0,4.0
30335,67528,startup_6,NaN,"Dec 15, 2010",Current Employee,Senior Test Lead,"It's a competitive work place, with overload w...","Smart people around you, can learn from them","Politics, weak moral, leaning loyalty",NaN,2.0,NaN,3.0,3.5,3.0,0,3.0

In [13]:
frames = [train, test]

df_categories = pd.concat(frames)

In [14]:
df_categories.isnull().sum()

ID                    0
Place                 0
location          20879
date                  0
status                0
job_title             0
summary             103
positives             0
negatives             1
advice_to_mgmt    25796
score_1            3186
score_2            6050
score_3            3169
score_4            3191
score_5            3485
score_6               0
overall               0
dtype: int64

In [15]:
df_categories = df_categories.rename(columns={'score_1':'work-balance', 'score_2':'culture-values', 'score_3':'carreer-opportunities', 'score_4':'comp-benefit', 'score_5':'senior-mangemnet', 'score_6':'helpful-count'})

In [16]:
df_categories.head()

,ID,Place,location,date,status,job_title,summary,positives,negatives,advice_to_mgmt,work-balance,culture-values,carreer-opportunities,comp-benefit,senior-mangemnet,helpful-count,overall
0,1,startup_1,NaN,"Dec 11, 2018",Current Employee,Anonymous Employee,Best Company to work for,People are smart and friendly,Bureaucracy is slowing things down,NaN,4.0,5.0,5.0,4.0,5.0,0,5.0
1,2,startup_1,"Mountain View, CA","Jun 21, 2013",Former Employee,Program Manager,"Moving at the speed of light, burn out is inev...","1) Food, food, food. 15+ cafes on main campus ...",1) Work/life balance. What balance? All those ...,1) Don't dismiss emotional intelligence and ad...,2.0,3.0,3.0,5.0,3.0,2094,5.0
2,3,startup_1,"New York, NY","May 10, 2014",Current Employee,Software Engineer III,Great balance between big-company security and...,"* If you're a software engineer, you're among ...","* It *is* becoming larger, and with it comes g...",Keep the focus on the user. Everything else wi...,5.0,4.0,5.0,5.0,4.0,949,5.0
3,4,startup_1,"Mountain View, CA","Feb 8, 2015",Current Employee,Anonymous Employee,The best place I've worked and also the most d...,You can't find a more well-regarded company th...,I live in SF so the commute can take between 1...,Keep on NOT micromanaging - that is a huge ben...,2.0,5.0,5.0,4.0,5.0,498,4.0
4,10,startup_1,NaN,"Dec 9, 2018",Current Employee,Anonymous Employee,Execellent for engineers,Impact driven. Best tech in the world.,Size matters. Engineers are a bit disconnected...,NaN,5.0,5.0,5.0,5.0,5.0,0,4.0

In [18]:
df_categories.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 59608 entries, 0 to 29271
Data columns (total 17 columns):
ID                       59608 non-null int64
Place                    59608 non-null object
location                 38729 non-null object
date                     59608 non-null object
status                   59608 non-null object
job_title                59608 non-null object
summary                  59505 non-null object
positives                59608 non-null object
negatives                59607 non-null object
advice_to_mgmt           33812 non-null object
work-balance             56422 non-null float64
culture-values           53558 non-null float64
carreer-opportunities    56439 non-null float64
comp-benefit             56417 non-null float64
senior-mangemnet         56123 non-null float64
helpful-count            59608 non-null int64
overall                  59608 non-null float64
dtypes: float64(6), int64(2), object(9)
memory usage: 8.2+ MB