In [11]:
import pandas as pd

In [12]:
path_train = '/Users/celinegianduzzo/code/theresa-sporn/WorkforceSentimentMonitoring/raw_data/train.csv'

train = pd.read_csv(path_train)

In [13]:
path_test = '/Users/celinegianduzzo/code/theresa-sporn/WorkforceSentimentMonitoring/raw_data/test.csv'

test = pd.read_csv(path_test)

In [4]:
train.shape

(30336, 17)

In [5]:
test.shape

(29272, 16)

In [20]:
overall_rating = pd.DataFrame(train)

In [32]:
overall_rating.drop(columns=['score_1', 'score_2', 'score_3', 'score_4', 'score_5', 'score_6'])

,ID,Place,location,date,status,job_title,summary,positives,negatives,advice_to_mgmt,overall
0,1,startup_1,NaN,"Dec 11, 2018",Current Employee,Anonymous Employee,Best Company to work for,People are smart and friendly,Bureaucracy is slowing things down,NaN,5.0
1,2,startup_1,"Mountain View, CA","Jun 21, 2013",Former Employee,Program Manager,"Moving at the speed of light, burn out is inev...","1) Food, food, food. 15+ cafes on main campus ...",1) Work/life balance. What balance? All those ...,1) Don't dismiss emotional intelligence and ad...,5.0
2,3,startup_1,"New York, NY","May 10, 2014",Current Employee,Software Engineer III,Great balance between big-company security and...,"* If you're a software engineer, you're among ...","* It *is* becoming larger, and with it comes g...",Keep the focus on the user. Everything else wi...,5.0
3,4,startup_1,"Mountain View, CA","Feb 8, 2015",Current Employee,Anonymous Employee,The best place I've worked and also the most d...,You can't find a more well-regarded company th...,I live in SF so the commute can take between 1...,Keep on NOT micromanaging - that is a huge ben...,4.0
4,10,startup_1,NaN,"Dec 9, 2018",Current Employee,Anonymous Employee,Execellent for engineers,Impact driven. Best tech in the world.,Size matters. Engineers are a bit disconnected...,NaN,4.0
...,...,...,...,...,...,...,...,...,...,...,...
30331,67522,startup_6,NaN,"Dec 22, 2010",Former Employee,Senior Project Managet,Microsoft Services is bad.,MS is a good company but hire wrong people. Wo...,Senior management has no leadership and very o...,Major management revamp esp in APAC. It's not ...,2.0
30332,67524,startup_6,NaN,"Dec 17, 2010",Former Employee,Senior Program Manager,Good company.,"Good benefits package, huge customer base.","Politics, very slow, lots of dead wood.",Move on.,4.0
30333,67525,startup_6,NaN,"Dec 16, 2010",Former Employee,Anonymous Employee,Enriching experience for a beginner but bad fo...,"-Access to a wide range of technologies, compl...",-Testers(SDET's ) do not get as many opportuni...,Make the company leaner and Meaner. (which wou...,3.0
30334,67527,startup_6,NaN,"Dec 15, 2010",Current Employee,Account Manager,Good Place to Work,Nice place to work. Good atmosphere with advan...,Management confusion at times with vision for ...,NaN,4.0
30335,67528,startup_6,NaN,"Dec 15, 2010",Current Employee,Senior Test Lead,"It's a competitive work place, with overload w...","Smart people around you, can learn from them","Politics, weak moral, leaning loyalty",NaN,3.0

In [26]:
train = train.drop(columns=['overall'])

In [27]:
train

,ID,Place,location,date,status,job_title,summary,positives,negatives,advice_to_mgmt,score_1,score_2,score_3,score_4,score_5,score_6
0,1,startup_1,NaN,"Dec 11, 2018",Current Employee,Anonymous Employee,Best Company to work for,People are smart and friendly,Bureaucracy is slowing things down,NaN,4.0,5.0,5.0,4.0,5.0,0
6,17,startup_1,NaN,"Nov 29, 2018",Current Employee,Anonymous Employee,Review of Google,"The people are great to work with, good perks.",Wide variety in experience based on team.,NaN,4.0,5.0,5.0,5.0,4.0,2
7,18,startup_1,NaN,"Dec 2, 2018",Former Employee,Anonymous Employee,Analysts,"Good managers, benefits , some support, nice a...","Long hours, far locations, a lot of work",NaN,NaN,NaN,2.0,NaN,NaN,1
8,19,startup_1,NaN,"Dec 1, 2018",Former Employee,Anonymous Employee,Great Company With No Down Sides,Really fun work environment with startup,Really no down sides that I saw.,NaN,5.0,5.0,5.0,5.0,5.0,1
9,24,startup_1,NaN,"Nov 30, 2018",Current Employee,Anonymous Employee,Software Engineer,Awesome job environment to work in,Pressure is there for some parts,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30331,67522,startup_6,NaN,"Dec 22, 2010",Former Employee,Senior Project Managet,Microsoft Services is bad.,MS is a good company but hire wrong people. Wo...,Senior management has no leadership and very o...,Major management revamp esp in APAC. It's not ...,3.0,NaN,1.5,2.0,1.0,0
30332,67524,startup_6,NaN,"Dec 17, 2010",Former Employee,Senior Program Manager,Good company.,"Good benefits package, huge customer base.","Politics, very slow, lots of dead wood.",Move on.,3.5,NaN,3.5,4.0,4.0,0
30333,67525,startup_6,NaN,"Dec 16, 2010",Former Employee,Anonymous Employee,Enriching experience for a beginner but bad fo...,"-Access to a wide range of technologies, compl...",-Testers(SDET's ) do not get as many opportuni...,Make the company leaner and Meaner. (which wou...,3.0,NaN,4.0,4.0,2.0,0
30334,67527,startup_6,NaN,"Dec 15, 2010",Current Employee,Account Manager,Good Place to Work,Nice place to work. Good atmosphere with advan...,Management confusion at times with vision for ...,NaN,3.0,NaN,4.0,4.5,3.5,0
30335,67528,startup_6,NaN,"Dec 15, 2010",Current Employee,Senior Test Lead,"It's a competitive work place, with overload w...","Smart people around you, can learn from them","Politics, weak moral, leaning loyalty",NaN,2.0,NaN,3.0,3.5,3.0,0

In [33]:
frames = [train, test]

df_categories = pd.concat(frames)

In [34]:
df_categories.isnull().sum()

ID                    0
Place                 0
location          20877
date                  0
status                0
job_title             0
summary             103
positives             0
negatives             1
advice_to_mgmt    25794
score_1            3185
score_2            6049
score_3            3168
score_4            3190
score_5            3484
score_6               0
dtype: int64

In [35]:
df_categories = df_categories.rename(columns={'score_1':'work-balance', 'score_2':'culture-values', 'score_3':'carreer-opportunities', 'score_4':'comp-benefit', 'score_5':'senior-mangemnet', 'score_6':'helpful-count'})

In [36]:
df_categories.head()

,ID,Place,location,date,status,job_title,summary,positives,negatives,advice_to_mgmt,work-balance,culture-values,carreer-opportunities,comp-benefit,senior-mangemnet,helpful-count
0,1,startup_1,NaN,"Dec 11, 2018",Current Employee,Anonymous Employee,Best Company to work for,People are smart and friendly,Bureaucracy is slowing things down,NaN,4.0,5.0,5.0,4.0,5.0,0
6,17,startup_1,NaN,"Nov 29, 2018",Current Employee,Anonymous Employee,Review of Google,"The people are great to work with, good perks.",Wide variety in experience based on team.,NaN,4.0,5.0,5.0,5.0,4.0,2
7,18,startup_1,NaN,"Dec 2, 2018",Former Employee,Anonymous Employee,Analysts,"Good managers, benefits , some support, nice a...","Long hours, far locations, a lot of work",NaN,NaN,NaN,2.0,NaN,NaN,1
8,19,startup_1,NaN,"Dec 1, 2018",Former Employee,Anonymous Employee,Great Company With No Down Sides,Really fun work environment with startup,Really no down sides that I saw.,NaN,5.0,5.0,5.0,5.0,5.0,1
9,24,startup_1,NaN,"Nov 30, 2018",Current Employee,Anonymous Employee,Software Engineer,Awesome job environment to work in,Pressure is there for some parts,NaN,NaN,NaN,NaN,NaN,NaN,0