In [1]:
import pandas as pd
import os

In [2]:
path_submission = '/Users/celinegianduzzo/code/theresa-sporn/WorkforceSentimentMonitoring/raw_data/sample_submission.csv'

In [3]:
submission = pd.read_csv(path_submission)

In [4]:
submission.shape

(29272, 2)

In [5]:
submission.tail()

          ID  overall
29267  66959        4
29268  66965        2
29269  66968        3
29270  66978        1
29271  66986        4

In [6]:
path_train = '/Users/celinegianduzzo/code/theresa-sporn/WorkforceSentimentMonitoring/raw_data/train.csv'

train = pd.read_csv(path_train)

In [7]:
path_test = '/Users/celinegianduzzo/code/theresa-sporn/WorkforceSentimentMonitoring/raw_data/test.csv'

test = pd.read_csv(path_test)

In [8]:
train.shape

(30336, 17)

In [9]:
test.shape

(29272, 16)

In [10]:
test = pd.merge(test, submission, on=['ID'])

In [11]:
test

,ID,Place,location,date,status,job_title,summary,positives,negatives,advice_to_mgmt,score_1,score_2,score_3,score_4,score_5,score_6,overall
0,5,startup_1,"Los Angeles, CA","Jul 19, 2018",Former Employee,Software Engineer,"Unique, one of a kind dream job",Google is a world of its own. At every other c...,"If you don't work in MTV (HQ), you will be giv...",Promote managers into management for their man...,5,5,5,5,5,49,5
1,6,startup_1,"Mountain View, CA","Dec 9, 2018",Former Employee,SDE2,NICE working in GOOGLE as an INTERN,"People are not that busy, so they are nice to ...",Food is not good as I expected. People said it...,NaN,4,4,4,5,4,1,4
2,7,startup_1,"New York, NY","Dec 11, 2018",Current Employee,Software Engineer,Software engineer,Great working environment. Good work life balance,Usual big company problems. Hierarchy.,NaN,5,4,4,5,4,0,4
3,8,startup_1,NaN,"Dec 11, 2018",Former Employee,Anonymous Employee,great place to work and progress,"work culture, benefits, growth, people,",No cons that i can think of,NaN,5,5,5,5,5,0,5
4,9,startup_1,"New York, NY","Dec 10, 2018",Current Employee,Anonymous Employee,Google Surpasses Realistic Expectations,Great products. Vision you can feel good about...,Younger employees complaining about the compan...,NaN,5,5,5,5,5,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29267,66959,startup_6,NaN,"Jun 4, 2012",Current Employee,Solution Specialist,great place to grow!,Great health benefits. Many internal job oppor...,Red Tape. Tough to negotiate internal politics...,NaN,4,4,5,4,4,0,4
29268,66965,startup_6,NaN,"May 31, 2012",Current Employee,Senior Program Manager,An ocean of opportunities,diverse set of people and problems they solve....,sometimes feels like a behemoth trying to get ...,align workgroups and incentives better to crea...,1,3,5,4,2,0,2
29269,66968,startup_6,NaN,"Jun 1, 2012",Current Employee,Software Development Engineer In Test (SDET),Tech Gaint,Equip its employees wid huge salaries :D,High qualification required to join it,Good Going....try searching new and bigger tal...,3,3,3,3,3,0,3
29270,66978,startup_6,NaN,"Jun 8, 2012",Former Employee,Senior Systems Engineer,Terrible,They had great health benefits (no longer im t...,* 14 hour days * no idea how to run a service ...,Learn to excel (no pun intended) and ignore mo...,1,1,1,3,1,3,1
29271,66986,startup_6,Hyderabad (India),"May 26, 2012",Current Employee,Program Manager,Microsoft is a good place to work,Very structured organization Market focused pr...,Growth is a little slow - Good structure impli...,NaN,4,4,4,3,4,0,4

In [12]:
train

,ID,Place,location,date,status,job_title,summary,positives,negatives,advice_to_mgmt,score_1,score_2,score_3,score_4,score_5,score_6,overall
0,1,startup_1,NaN,"Dec 11, 2018",Current Employee,Anonymous Employee,Best Company to work for,People are smart and friendly,Bureaucracy is slowing things down,NaN,4.0,5.0,5.0,4.0,5.0,0,5.0
1,2,startup_1,"Mountain View, CA","Jun 21, 2013",Former Employee,Program Manager,"Moving at the speed of light, burn out is inev...","1) Food, food, food. 15+ cafes on main campus ...",1) Work/life balance. What balance? All those ...,1) Don't dismiss emotional intelligence and ad...,2.0,3.0,3.0,5.0,3.0,2094,5.0
2,3,startup_1,"New York, NY","May 10, 2014",Current Employee,Software Engineer III,Great balance between big-company security and...,"* If you're a software engineer, you're among ...","* It *is* becoming larger, and with it comes g...",Keep the focus on the user. Everything else wi...,5.0,4.0,5.0,5.0,4.0,949,5.0
3,4,startup_1,"Mountain View, CA","Feb 8, 2015",Current Employee,Anonymous Employee,The best place I've worked and also the most d...,You can't find a more well-regarded company th...,I live in SF so the commute can take between 1...,Keep on NOT micromanaging - that is a huge ben...,2.0,5.0,5.0,4.0,5.0,498,4.0
4,10,startup_1,NaN,"Dec 9, 2018",Current Employee,Anonymous Employee,Execellent for engineers,Impact driven. Best tech in the world.,Size matters. Engineers are a bit disconnected...,NaN,5.0,5.0,5.0,5.0,5.0,0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30331,67522,startup_6,NaN,"Dec 22, 2010",Former Employee,Senior Project Managet,Microsoft Services is bad.,MS is a good company but hire wrong people. Wo...,Senior management has no leadership and very o...,Major management revamp esp in APAC. It's not ...,3.0,NaN,1.5,2.0,1.0,0,2.0
30332,67524,startup_6,NaN,"Dec 17, 2010",Former Employee,Senior Program Manager,Good company.,"Good benefits package, huge customer base.","Politics, very slow, lots of dead wood.",Move on.,3.5,NaN,3.5,4.0,4.0,0,4.0
30333,67525,startup_6,NaN,"Dec 16, 2010",Former Employee,Anonymous Employee,Enriching experience for a beginner but bad fo...,"-Access to a wide range of technologies, compl...",-Testers(SDET's ) do not get as many opportuni...,Make the company leaner and Meaner. (which wou...,3.0,NaN,4.0,4.0,2.0,0,3.0
30334,67527,startup_6,NaN,"Dec 15, 2010",Current Employee,Account Manager,Good Place to Work,Nice place to work. Good atmosphere with advan...,Management confusion at times with vision for ...,NaN,3.0,NaN,4.0,4.5,3.5,0,4.0
30335,67528,startup_6,NaN,"Dec 15, 2010",Current Employee,Senior Test Lead,"It's a competitive work place, with overload w...","Smart people around you, can learn from them","Politics, weak moral, leaning loyalty",NaN,2.0,NaN,3.0,3.5,3.0,0,3.0

In [13]:
frames = [train, test]

df_categories = pd.concat(frames)

In [14]:
df_categories = df_categories.rename(columns={'score_1':'work-balance', 'score_2':'culture-values', 'score_3':'career-opportunities', 'score_4':'comp-benefits', 'score_5':'senior-mgmt', 'score_6':'helpful-count'})

In [15]:
df = df_categories.drop(columns=['ID', 'Place', 'location', 'date', 'status', 'job_title', 'helpful-count'])
df

,summary,positives,negatives,advice_to_mgmt,work-balance,culture-values,career-opportunities,comp-benefits,senior-mgmt,overall
0,Best Company to work for,People are smart and friendly,Bureaucracy is slowing things down,NaN,4.0,5.0,5.0,4.0,5.0,5.0
1,"Moving at the speed of light, burn out is inev...","1) Food, food, food. 15+ cafes on main campus ...",1) Work/life balance. What balance? All those ...,1) Don't dismiss emotional intelligence and ad...,2.0,3.0,3.0,5.0,3.0,5.0
2,Great balance between big-company security and...,"* If you're a software engineer, you're among ...","* It *is* becoming larger, and with it comes g...",Keep the focus on the user. Everything else wi...,5.0,4.0,5.0,5.0,4.0,5.0
3,The best place I've worked and also the most d...,You can't find a more well-regarded company th...,I live in SF so the commute can take between 1...,Keep on NOT micromanaging - that is a huge ben...,2.0,5.0,5.0,4.0,5.0,4.0
4,Execellent for engineers,Impact driven. Best tech in the world.,Size matters. Engineers are a bit disconnected...,NaN,5.0,5.0,5.0,5.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...
29267,great place to grow!,Great health benefits. Many internal job oppor...,Red Tape. Tough to negotiate internal politics...,NaN,4.0,4.0,5.0,4.0,4.0,4.0
29268,An ocean of opportunities,diverse set of people and problems they solve....,sometimes feels like a behemoth trying to get ...,align workgroups and incentives better to crea...,1.0,3.0,5.0,4.0,2.0,2.0
29269,Tech Gaint,Equip its employees wid huge salaries :D,High qualification required to join it,Good Going....try searching new and bigger tal...,3.0,3.0,3.0,3.0,3.0,3.0
29270,Terrible,They had great health benefits (no longer im t...,* 14 hour days * no idea how to run a service ...,Learn to excel (no pun intended) and ignore mo...,1.0,1.0,1.0,3.0,1.0,1.0
29271,Microsoft is a good place to work,Very structured organization Market focused pr...,Growth is a little slow - Good structure impli...,NaN,4.0,4.0,4.0,3.0,4.0,4.0

In [16]:
df.shape

(59608, 10)

In [17]:
feature_cols = ['summary', 'positives', 'negatives', 'advice_to_mgmt']
df['text'] = df[feature_cols].astype('U').agg(' '.join, axis=1)
df

,summary,positives,negatives,advice_to_mgmt,work-balance,culture-values,career-opportunities,comp-benefits,senior-mgmt,overall,text
0,Best Company to work for,People are smart and friendly,Bureaucracy is slowing things down,NaN,4.0,5.0,5.0,4.0,5.0,5.0,Best Company to work for People are smart and ...
1,"Moving at the speed of light, burn out is inev...","1) Food, food, food. 15+ cafes on main campus ...",1) Work/life balance. What balance? All those ...,1) Don't dismiss emotional intelligence and ad...,2.0,3.0,3.0,5.0,3.0,5.0,"Moving at the speed of light, burn out is inev..."
2,Great balance between big-company security and...,"* If you're a software engineer, you're among ...","* It *is* becoming larger, and with it comes g...",Keep the focus on the user. Everything else wi...,5.0,4.0,5.0,5.0,4.0,5.0,Great balance between big-company security and...
3,The best place I've worked and also the most d...,You can't find a more well-regarded company th...,I live in SF so the commute can take between 1...,Keep on NOT micromanaging - that is a huge ben...,2.0,5.0,5.0,4.0,5.0,4.0,The best place I've worked and also the most d...
4,Execellent for engineers,Impact driven. Best tech in the world.,Size matters. Engineers are a bit disconnected...,NaN,5.0,5.0,5.0,5.0,5.0,4.0,Execellent for engineers Impact driven. Best t...
...,...,...,...,...,...,...,...,...,...,...,...
29267,great place to grow!,Great health benefits. Many internal job oppor...,Red Tape. Tough to negotiate internal politics...,NaN,4.0,4.0,5.0,4.0,4.0,4.0,great place to grow! Great health benefits. Ma...
29268,An ocean of opportunities,diverse set of people and problems they solve....,sometimes feels like a behemoth trying to get ...,align workgroups and incentives better to crea...,1.0,3.0,5.0,4.0,2.0,2.0,An ocean of opportunities diverse set of peopl...
29269,Tech Gaint,Equip its employees wid huge salaries :D,High qualification required to join it,Good Going....try searching new and bigger tal...,3.0,3.0,3.0,3.0,3.0,3.0,Tech Gaint Equip its employees wid huge salari...
29270,Terrible,They had great health benefits (no longer im t...,* 14 hour days * no idea how to run a service ...,Learn to excel (no pun intended) and ignore mo...,1.0,1.0,1.0,3.0,1.0,1.0,Terrible They had great health benefits (no lo...
29271,Microsoft is a good place to work,Very structured organization Market focused pr...,Growth is a little slow - Good structure impli...,NaN,4.0,4.0,4.0,3.0,4.0,4.0,Microsoft is a good place to work Very structu...

In [18]:
categories = ['work-balance', 'culture-values', 'career-opportunities', 'comp-benefits', 'senior-mgmt', 'overall']
df = df.dropna(axis=0, subset=categories)
df = df.drop_duplicates()
df.head()

,summary,positives,negatives,advice_to_mgmt,work-balance,culture-values,career-opportunities,comp-benefits,senior-mgmt,overall,text
0,Best Company to work for,People are smart and friendly,Bureaucracy is slowing things down,NaN,4.0,5.0,5.0,4.0,5.0,5.0,Best Company to work for People are smart and ...
1,"Moving at the speed of light, burn out is inev...","1) Food, food, food. 15+ cafes on main campus ...",1) Work/life balance. What balance? All those ...,1) Don't dismiss emotional intelligence and ad...,2.0,3.0,3.0,5.0,3.0,5.0,"Moving at the speed of light, burn out is inev..."
2,Great balance between big-company security and...,"* If you're a software engineer, you're among ...","* It *is* becoming larger, and with it comes g...",Keep the focus on the user. Everything else wi...,5.0,4.0,5.0,5.0,4.0,5.0,Great balance between big-company security and...
3,The best place I've worked and also the most d...,You can't find a more well-regarded company th...,I live in SF so the commute can take between 1...,Keep on NOT micromanaging - that is a huge ben...,2.0,5.0,5.0,4.0,5.0,4.0,The best place I've worked and also the most d...
4,Execellent for engineers,Impact driven. Best tech in the world.,Size matters. Engineers are a bit disconnected...,NaN,5.0,5.0,5.0,5.0,5.0,4.0,Execellent for engineers Impact driven. Best t...

In [21]:
categories = ['work-balance', 'culture-values', 'career-opportunities', 'comp-benefits', 'senior-mgmt']
df[categories] = df[categories].astype('uint8')

In [22]:
df.shape

(52815, 11)

In [23]:
df.isnull().sum()

summary                    81
positives                   0
negatives                   1
advice_to_mgmt          22683
work-balance                0
culture-values              0
career-opportunities        0
comp-benefits               0
senior-mgmt                 0
overall                     0
text                        0
dtype: int64